//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvantApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Messages()
        {
            this.MessageProcessing = new HashSet<MessageProcessing>();
            this.PopularMessages = new HashSet<PopularMessages>();
        }
    
        public int IdMessage { get; set; }
        public System.DateTime DateTime { get; set; }
        public int MessageUser { get; set; }
        public int TypeMessage { get; set; }
        public string MessageText { get; set; }
        public int MessegeEvent { get; set; }
        public string MediaContent { get; set; }
        public bool Processed { get; set; }
        public int MessageCategories { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual MessageCategories MessageCategories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageProcessing> MessageProcessing { get; set; }
        public virtual TypeMessage TypeMessage1 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PopularMessages> PopularMessages { get; set; }
    }
}
