//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvantApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageProcessing
    {
        public int IdMessageProcessing { get; set; }
        public int MessageProcessingStaff { get; set; }
        public int MessageProcessingMessage { get; set; }
        public int MessageProcessingStatusMessage { get; set; }
        public string answerComment { get; set; }
    
        public virtual Messages Messages { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual StatusMessage StatusMessage { get; set; }
    }
}
