//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvantApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CallPresidentEntities : DbContext
    {
        public CallPresidentEntities()
            : base("name=CallPresidentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<FederalDistricts> FederalDistricts { get; set; }
        public virtual DbSet<MessageCategories> MessageCategories { get; set; }
        public virtual DbSet<MessageProcessing> MessageProcessing { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<PopularGroup> PopularGroup { get; set; }
        public virtual DbSet<PopularMessages> PopularMessages { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<StaffEvent> StaffEvent { get; set; }
        public virtual DbSet<StatusMessage> StatusMessage { get; set; }
        public virtual DbSet<TypeMessage> TypeMessage { get; set; }
        public virtual DbSet<TypeStaff> TypeStaff { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
