//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvantApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopularMessages
    {
        public int IdPopularMessage { get; set; }
        public int PopularMessageMessageId { get; set; }
        public int PopularMessagePopularGroup { get; set; }
        public int vote { get; set; }
    
        public virtual Messages Messages { get; set; }
        public virtual PopularGroup PopularGroup { get; set; }
    }
}
